### ISSUE TITLE
Fresh install gets ImportError: cannot import name cli

### ISSUE THREAD

**Issue by scottleibrand** [openaps/openaps#1]
Clone a new copy of openaps.  cd into it and run sudo python setup.py install.  Try to run openaps, and you get:

pi@raspberrypi3 ~ $ openaps
Traceback (most recent call last):
  File "/usr/local/bin/openaps", line 5, in <module>
    pkg_resources.run_script('openaps==0.0.0', 'openaps')
  File "/usr/local/lib/python2.7/dist-packages/setuptools-1.0-py2.7.egg/pkg_resources.py", line 492, in run_script
  File "/usr/local/lib/python2.7/dist-packages/setuptools-1.0-py2.7.egg/pkg_resources.py", line 1350, in run_script
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.0-py2.7.egg/EGG-INFO/scripts/openaps", line 36, in <module>
    from openaps import cli
ImportError: cannot import name cli
pi@raspberrypi3 ~ $

What else is needed to set up the package properly with proper PYTHONPATH etc.?  Can we make setup.py do that automatically, or document what's necessary in the appropriate place?

**Comment by scottleibrand** [comment]
Looks like there is no cli module in the openaps-0.0.0-py2.7.egg/openaps/ directory:

Out[1]: <module 'openaps' from '/usr/local/lib/python2.7/dist-packages/openaps-0.0.0-py2.7.egg/openaps/__init__.pyc'>
In [2]: openaps.
openaps.builtins  openaps.init

pi@raspberrypi3 /usr/local/lib/python2.7/dist-packages/openaps-0.0.0-py2.7.egg/openaps $ ls
builtins.py  builtins.pyc  config.py  config.pyc  configurable.py  configurable.pyc  __init__.py  init.py  __init__.pyc  init.pyc

**Comment by scottleibrand** [comment]
Submitted https://github.com/openaps/openaps/pull/2 with a fix/workaround.  Feel free to accept that or reject it and fix it properly.  :-)
