### ISSUE TITLE
Can't invoke oref0_glucose report | Python int too large to convert to C long 

### ISSUE THREAD

**Issue by garykidd** [openaps/openaps#106]
While attempting to configure openaps tools including that for using G5...following...http://openaps.readthedocs.io/en/dev/docs/walkthrough/phase-1/using-openaps-tools.html#g5-support

It should be noted that openaps use oref_glucose works without exception.

receive the following error.....

**pi@raspberrypi:~/APS000** $ openaps report add last_2_hours_cgm.json JSON cgm oref0_glucose --no-raw --hours 2

          added cgm://JSON/oref0_glucose/last_2_hours_cgm.json

**pi@raspberrypi:~/APS000** $ openaps report invoke last_2_hours_cgm.json
          
          cgm://JSON/oref0_glucose/last_2_hours_cgm.json

          last_2_hours_cgm.json raised Python int too large to convert to C long

          Traceback (most recent call last):

         File "/usr/local/bin/openaps-report", line 82, in <module>
         app( )
         File "/usr/local/lib/python2.7/dist-packages/openaps/cli/init.py", line 51, in call
         self.run(self.args)
         File "/usr/local/bin/openaps-report", line 75, in run
         output = app(args, self)
         File "/usr/local/lib/python2.7/dist-packages/openaps/cli/subcommand.py", line 52, in call
         return self.method.main(args, app)
         File "/usr/local/lib/python2.7/dist-packages/openaps/reports/invoke.py", line 40, in main
         output = task.method(args, app)
         File "/usr/local/lib/python2.7/dist-packages/openaps/uses/use.py", line 45, in call
         output = self.main(args, app)
         File "/usr/local/lib/python2.7/dist-packages/openaps/vendors/dexcom.py", line 536, in main
         for egv, raw in itertools.izip_longest(iter_glucose, iter_sensor):
         File "/usr/local/lib/python2.7/dist-packages/dexcom_reader/readdata.py", line 300, in      iter_records
         for x in reversed(xrange(start, end)):

         OverflowError: Python int too large to convert to C long

**Comment by jasoncalabrese** [comment]
Closed via #104
