### ISSUE TITLE
openaps use pump read_bg_targets

### ISSUE THREAD

**Issue by amazaheri** [openaps/openaps#12]
still trying to see if this pump setting related but getting the following exception:
Traceback (most recent call last):
  File "/usr/local/bin/openaps-use", line 10, in <module>
    execfile(__file__)
  File "/home/ubuntu/openaps/bin/openaps-use", line 63, in <module>
    app( )
  File "/home/ubuntu/openaps/openaps/cli/__init__.py", line 44, in __call__
    self.run(self.args)
  File "/home/ubuntu/openaps/bin/openaps-use", line 58, in run
    reporter(output)
  File "/home/ubuntu/openaps/openaps/reports/reporters/__init__.py", line 27, in __call__
    self.blob = self.serialize(data)
  File "/home/ubuntu/openaps/openaps/reports/reporters/__init__.py", line 25, in serialize
    return self.method.serialize(render(data), self)
  File "/home/ubuntu/openaps/openaps/reports/reporters/JSON.py", line 8, in serialize
    return json.dumps(blob, indent=2, default=date_handler)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 443, in _iterencode
    for chunk in _iterencode(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 440, in _iterencode
    raise ValueError("Circular reference detected")
ValueError: Circular reference detected

**Comment by amazaheri** [comment]
Latest build resolved this issue, we can close it.
