### ISSUE TITLE
< 100 records in pump

### ISSUE THREAD

**Issue by eszcloud** [openaps/openaps#43]
Medtronic 522 v2.4A

The pump has a cleared history with < 100 entries.

```
pi@raspberrypi ~/myopenaps $ openaps use pump iter_pump 100
Traceback (most recent call last):
  File "/usr/local/bin/openaps-use", line 5, in <module>
    pkg_resources.run_script('openaps==0.0.6', 'openaps-use')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.6-py2.7.egg/EGG-INFO/scripts/openaps-use", line 63, in <module>
    app( )
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.6-py2.7.egg/openaps/cli/__init__.py", line 44, in __call__
    self.run(self.args)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.6-py2.7.egg/EGG-INFO/scripts/openaps-use", line 57, in run
    output = app(args, self)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.6-py2.7.egg/openaps/uses/__init__.py", line 92, in __call__
    return self.method.selected(args)(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.6-py2.7.egg/openaps/uses/__init__.py", line 31, in __call__
    return self.method(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.6-py2.7.egg/openaps/uses/use.py", line 26, in __call__
    output = self.main(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.6-py2.7.egg/openaps/vendors/medtronic.py", line 341, in main
    for rec in self.range( ):
  File "/usr/local/lib/python2.7/dist-packages/decocare-0.0.18_dev-py2.7.egg/decocare/models/__init__.py", line 63, in __call__
    for record in page:
  File "/usr/local/lib/python2.7/dist-packages/decocare-0.0.18_dev-py2.7.egg/decocare/models/__init__.py", line 42, in download_page
    for record in self.find_records(page):
  File "/usr/local/lib/python2.7/dist-packages/decocare-0.0.18_dev-py2.7.egg/decocare/models/__init__.py", line 133, in find_records
    decoder = history.HistoryPage(response.data, self.inst)
  File "/usr/local/lib/python2.7/dist-packages/decocare-0.0.18_dev-py2.7.egg/decocare/history.py", line 744, in __init__
    if lib.BangInt(crc) != computed:
  File "/usr/local/lib/python2.7/dist-packages/decocare-0.0.18_dev-py2.7.egg/decocare/lib.py", line 235, in BangInt
    ( x, y ) = ints
ValueError: need more than 0 values to unpack
pi@raspberrypi ~/myopenaps $ ^C
pi@raspberrypi ~/myopenaps $ openaps use pump iter_pump 1
[
  {
    "_type": "BGReceived",
    "link": "909967",
    "_description": "BGReceived 2015-09-14T10:28:16 head[2], body[3] op[0x3f]",
    "timestamp": "2015-09-14T10:28:16",
    "_body": "909967",
    "_head": "3f0a",
    "amount": 82,
    "_date": "905c4a6e0f"
  },
  {
    "_type": "CalBGForPH",
    "_description": "CalBGForPH 2015-09-14T10:28:16 head[2], body[0] op[0x0a]",
    "timestamp": "2015-09-14T10:28:16",
    "_body": "",
    "_head": "0a52",
    "amount": 82,
    "_date": "905c2a6e0f"
  }
]pi@raspberrypi ~/myopenaps $ openaps use pump iter_pump 10
[
  {
    "_type": "BGReceived",
    "link": "909967",
    "_description": "BGReceived 2015-09-14T10:28:16 head[2], body[3] op[0x3f]",
    "timestamp": "2015-09-14T10:28:16",
    "_body": "909967",
    "_head": "3f0a",
    "amount": 82,
    "_date": "905c4a6e0f"
  },
  {
    "_type": "CalBGForPH",
    "_description": "CalBGForPH 2015-09-14T10:28:16 head[2], body[0] op[0x0a]",
    "timestamp": "2015-09-14T10:28:16",
    "_body": "",
    "_head": "0a52",
    "amount": 82,
    "_date": "905c2a6e0f"
  },
  {
    "_type": "Model522ResultTotals",
    "_description": "Model522ResultTotals 2015-09-14T00:00:00 head[1], body[41] op[0x6d]",
    "timestamp": "2015-09-14T00:00:00",
    "_body": "0500c691fb0200000000000000000000000000000000000000000000000000000000000c00e8000000",
    "_head": "6d",
    "_date": "8d8f"
  },
  {
    "_type": "MResultTotals",
    "_description": "MResultTotals 2015-09-14T00:00:00 head[5], body[0] op[0x07]",
    "timestamp": "2015-09-14T00:00:00",
    "_body": "",
    "_head": "0700000000",
    "_date": "8d8f"
  },
  {
    "_type": "BGReceived",
    "link": "909967",
    "_description": "BGReceived 2015-09-13T23:57:58 head[2], body[3] op[0x3f]",
    "timestamp": "2015-09-13T23:57:58",
    "_body": "909967",
    "_head": "3f1f",
    "amount": 251,
    "_date": "ba79776d0f"
  },
  {
    "_type": "CalBGForPH",
    "_description": "CalBGForPH 2015-09-13T23:57:58 head[2], body[0] op[0x0a]",
    "timestamp": "2015-09-13T23:57:58",
    "_body": "",
    "_head": "0afb",
    "amount": 251,
    "_date": "ba79376d0f"
  },
  {
    "_type": "BGReceived",
    "link": "909967",
    "_description": "BGReceived 2015-09-13T09:18:48 head[2], body[3] op[0x3f]",
    "timestamp": "2015-09-13T09:18:48",
    "_body": "909967",
    "_head": "3f12",
    "amount": 145,
    "_date": "b052296d0f"
  },
  {
    "_type": "CalBGForPH",
    "_description": "CalBGForPH 2015-09-13T09:18:48 head[2], body[0] op[0x0a]",
    "timestamp": "2015-09-13T09:18:48",
    "_body": "",
    "_head": "0a91",
    "amount": 145,
    "_date": "b052296d0f"
  },
  {
    "_type": "Model522ResultTotals",
    "_description": "Model522ResultTotals 2015-09-13T00:00:00 head[1], body[41] op[0x6d]",
    "timestamp": "2015-09-13T00:00:00",
    "_body": "0500c88bee0300000000000000000000000000000000000000000000000000000000000c00e8000000",
    "_head": "6d",
    "_date": "8c8f"
  },
  {
    "_type": "MResultTotals",
    "_description": "MResultTotals 2015-09-13T00:00:00 head[5], body[0] op[0x07]",
    "timestamp": "2015-09-13T00:00:00",
    "_body": "",
    "_head": "0700000000",
    "_date": "8c8f"
  },
  {
    "_type": "BGReceived",
    "link": "909967",
    "_description": "BGReceived 2015-09-12T23:32:40 head[2], body[3] op[0x3f]",
    "timestamp": "2015-09-12T23:32:40",
    "_body": "909967",
    "_head": "3f1b",
    "amount": 223,
    "_date": "a860f76c0f"
  }
]pi@raspberrypi ~/myopenaps $
```

**Comment by bewest** [comment]
Ouch!  Good catch!
