### ISSUE TITLE
Can not run command read_clock

### ISSUE THREAD

**Issue by esteward** [openaps/openaps#5]
pi@raspberrypi ~/elliottaps $ openaps use pump read_clock
PowerControl SERIAL 624446
Traceback (most recent call last):
  File "/usr/local/bin/openaps-use", line 8, in <module>
    execfile(__file__)
  File "/home/pi/openaps/bin/openaps-use", line 62, in <module>
    app( )
  File "/home/pi/openaps/openaps/cli/__init__.py", line 41, in __call__
    self.run(self.args)
  File "/home/pi/openaps/bin/openaps-use", line 56, in run
    output = app(args, self)
  File "/home/pi/openaps/openaps/uses/__init__.py", line 70, in __call__
    return self.method.selected(args)(args, app)
  File "/home/pi/openaps/openaps/uses/__init__.py", line 31, in __call__
    return self.method(args, app)
  File "/home/pi/openaps/openaps/uses/use.py", line 23, in __call__
    output = self.main(args, app)
  File "/home/pi/openaps/openaps/vendors/medtronic.py", line 181, in main
    return self.pump.model.read_clock( )
AttributeError: 'ReadPumpModel' object has no attribute 'read_clock'

**Comment by esteward** [comment]
This issue was fixed with a git pull from decoding-carelink
