### ISSUE TITLE
SyntaxError: '<' operator not allowed in environment markers

### ISSUE THREAD

**Issue by dhermanns** [openaps/openaps#95]
I got this error when trying to build openaps from source on the Raspberry 3 with raspbian os:

{code}
Installed /tmp/easy_install-j8XR62/mock-2.0.0/pbr-1.10.0-py2.7.egg
Marker evaluation failed, see the following error.  For more information see: http://docs.openstack.org/developer/pbr/compatibility.html#evaluate-marker
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/tmp/easy_install-j8XR62/mock-2.0.0/pbr-1.10.0-py2.7.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/tmp/easy_install-j8XR62/mock-2.0.0/pbr-1.10.0-py2.7.egg/pbr/util.py", line 248, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/tmp/easy_install-j8XR62/mock-2.0.0/pbr-1.10.0-py2.7.egg/pbr/util.py", line 431, in setup_cfg_to_setup_kwargs
    if pkg_resources.evaluate_marker('(%s)' % env_marker):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1306, in evaluate_marker
    return cls.interpret(parser.expr(text).totuple(1)[1])
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1341, in interpret
    return op(nodelist)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1254, in atom
    return cls.interpret(nodelist[2])
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1341, in interpret
    return op(nodelist)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1275, in comparison
    raise SyntaxError(msg)
SyntaxError: '<' operator not allowed in environment markers
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-j8XR62/mock-2.0.0/setup.cfg: SyntaxError: '<' operator not allowed in environment markers
{code}

What am I doing wrong?

**Comment by svola** [comment]
You need a newer version of setuptools.

http://docs.openstack.org/developer/pbr/compatibility.html#evaluate-marker

https://pypi.python.org/pypi/setuptools

I had the same problem (not with openapp though) and solved it by upgrading setuptools.
